In [12]:
import torch

x = torch.arange(12, dtype=torch.float32)
x.shape

X = x.reshape(3, -1)

print(X)

torch.zeros((2, 3, 4))

torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

print(X[-1], X[1:3], sep="\n")

X[1, 2] = 17

X[:2, :] = 12

torch.exp(x)

X = torch.arange(24, dtype=torch.float32).reshape((2, 3, 4))
Y = torch.arange(24, 48, dtype=torch.float32).reshape((2, 3, 4))
Z = torch.arange(48, 72, dtype=torch.float32).reshape((2, 4, 3))

print(X, Z)

tensor = torch.tensor([[[1, 2, 3]], [[4, 5, 6]]])

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([ 8.,  9., 10., 11.])
tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]]) tensor([[[48., 49., 50.],
         [51., 52., 53.],
         [54., 55., 56.],
         [57., 58., 59.]],

        [[60., 61., 62.],
         [63., 64., 65.],
         [66., 67., 68.],
         [69., 70., 71.]]])


In [13]:
import os

# os.makedirs(os.path.join("..", "data"), exist_ok=True)
data_file = os.path.join("/Users/thom/", "repos/d2l/d2l_exercises/data", "house_tiny.csv")
with open(data_file, "w") as f:
    f.write(
        """NumRooms,RoofType,Price
NA,NA,127500
2,NA,106000
4,Slate,178100
NA,NA,140000"""
    )

In [14]:
import pandas as pd

data = pd.read_csv(data_file)

print(data)

inputs, targets = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

inputs = inputs.fillna(inputs.mean())
print(inputs)

AttributeError: partially initialized module 'pandas' has no attribute 'core' (most likely due to a circular import)

In [ ]:
import pandas as pd

data = pd.read_csv("data/house_tiny.csv")

print(data)

inputs, targets = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

inputs = inputs.fillna(inputs.mean())
print(inputs)

In [ ]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()  # Assign a copy of A to B by allocating new memory
print(A)

sum_A = A.sum(dim=1, keepdim=True)
print(sum_A)

test_b = torch.tensor(
    [
        [
            3,
            3,
            3,
        ],
        [12, 12, 12],
    ],
    dtype=torch.float32,
)
print(test_b)

print(A / sum_A)
print(A / test_b)

A.cumsum(dim=0)

In [ ]:
x = torch.arange(3, dtype=torch.float32)
y = torch.ones(3, dtype=torch.float32)
print(x, y, torch.dot(x, y), sep="\n")

torch.sum(x * y)

In [ ]:
A.shape, x.shape, torch.mv(A, x), A @ x

In [ ]:
A = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = torch.tensor([[10, 11, 12], [13, 14, 15], [16, 17, 18]])

print("Origin:")
print(A, B, end="\n\n", sep="\n")

print("Transposed:")
print(A.T, B.T, end="\n\n", sep="\n")

print("Transposed before sum:")
print(A.T + B.T, end="\n\n", sep="\n")

print("Transposed after sum:")
print((A + B).T, end="\n\n", sep="\n")

In [ ]:
(A + A.T) == (A + A.T).T

In [ ]:
X = torch.arange(24).reshape(2, 3, 4)
print(X)
X.sum(dim=0)

In [ ]:
print("Original tensor:")
print(A)
print()

print("Summed up along dim 1 (column):")
print(A.sum(dim=1))
print()

print("The result:")
print(A / A.sum(dim=1))

In [ ]:
X = torch.arange(24).reshape(2, 3, 4)

print(X, end="\n\n")

print(X.sum(dim=0).shape)
print(X.sum(dim=1).shape)
print(X.sum(dim=2).shape)

In [ ]:
import math

S = torch.arange(4).reshape(2, 2).float()  # create a simple two-dim tensor
print(torch.linalg.norm(S))  # calc norm of it
print(math.sqrt(0**2 + 1**2 + 2**2 + 3**2))  # calc norm using plain mathematics

J = torch.arange(48).reshape(2, 3, 4, 2).float()  # create a complex 4-dim tensor
print(torch.linalg.norm(J))  # calc norm of it
print(
    math.sqrt(sum(i**2 for i in range(48)))
)  # calc norm using plain mathematics, which is not ideal

In [ ]:
import time

# Set the random seed for reproducibility
torch.manual_seed(0)

# Initialize the matrices
A = torch.randn(2**10, 2**16)
B = torch.randn(2**16, 2**5)
C = torch.randn(2**5, 2**14)

# measure the time used for running `(A @ B) @ C`
start_time = time.time()
# result_1 = (A @ B) @ C
end_time = time.time()
time_taken_1 = end_time - start_time
print(f"Time taken for (A @ B) @ C: {time_taken_1} seconds")

# measure the time used for running `A @ (B @ C)`
start_time = time.time()
# result_2 = A @ (B @ C)
end_time = time.time()
time_taken_2 = end_time - start_time
print(f"Time taken for A @ (B @ C): {time_taken_2} seconds")

In [ ]:
import time

# The simplified case

a = torch.arange(24).reshape(4, 6)
b = torch.arange(24, 36).reshape(6, 2)
c = torch.arange(36, 48).reshape(2, 6)

print(a, b, c, sep="\n")
print(a @ b)

A = torch.randn((2**10, 2**16))
B = torch.randn((2**16, 2**5))
C = torch.randn((2**5, 2**16))

start_time = time.perf_counter()
result_a = A @ B
time_taken = time.perf_counter() - start_time
print(f"The code took {time_taken} seconds to run.")

start_time = time.perf_counter()
result_b = A @ C.T
time_taken = time.perf_counter() - start_time
print(f"The code took {time_taken} seconds to run.")

In [ ]:
A = torch.randn(100, 200)
B = torch.randn(100, 200)
C = torch.randn(100, 200)

# stack A, B and C
T = torch.stack((A, B, C))

# slice out to recover B, as you can see they are equal.
B == T[1]

In [ ]:
import numpy as np
from sklearn.metrics import mean_squared_error


# Let's say our model is a simple linear regression model y = mx + c
def model(x, m, c):
    return m * x + c


# And our loss function is Mean Squared Error
def loss(y_actual, y_predicted):
    return mean_squared_error(y_actual, y_predicted)


# Let's say our input dataset is:
x_data = np.array([1, 2, 3, 4, 5])
y_data = np.array([2.2, 2.9, 3.9, 5.1, 6.1])

# Initialize our model's parameters
m = 1.0  # slope
c = 0.0  # intercept

# Make initial prediction
y_predicted = model(x_data, m, c)

# Calculate the loss
initial_loss = loss(y_data, y_predicted)

print(f'Initial Loss: {initial_loss}')

# Let's apply Gradient Descent
learning_rate = 0.01
num_iterations = 1_000

for i in range(num_iterations):
    # Compute the gradients
    grad_m = -2.0 * np.sum(x_data * (y_data - model(x_data, m, c)))
    grad_c = -2.0 * np.sum(y_data - model(x_data, m, c))

    # Update the parameters
    m = m - learning_rate * grad_m
    c = c - learning_rate * grad_c

    if i % 100 == 0:  # print progress every 100 steps
        y_predicted = model(x_data, m, c)
        current_loss = loss(y_data, y_predicted)
        print(f'Iteration {i}, Loss: {current_loss}')

print(f'Final parameters - m: {m}, c: {c}')

### Separation Line

The code cells above this line are created before 2023-08-09 

---

In [3]:
import torch

x = torch.arange(4.0)
x.requires_grad_()
x.grad
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [4]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [5]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [6]:
x.grad == 4 * x

tensor([True, True, True, True])